<?php
# This file was automatically generated by the MediaWiki 1.35.7
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "THMwiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The protocol and server name to use in fully-qualified URLs
$wgServer = "https://wiki.thfmu.com";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL paths to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogos = [ '1x' => "$wgResourceBasePath/resources/assets/wiki.png" ];

## UPO means: this is also a user preference option

$wgEnableEmail = false;
$wgEnableUserEmail = true; # UPO

$wgEmergencyContact = "apache@🌻.invalid";
$wgPasswordSender = "apache@🌻.invalid";

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype = "mysql";
$wgDBserver = "localhost";
$wgDBname = "wiki_thfmu_com";
$wgDBuser = "wiki_thfmu_com";
$wgDBpassword = "67AFja77EEfFhbaJ";

# MySQL specific settings
$wgDBprefix = "thmwiki_";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Shared database table
# This has no effect unless $wgSharedDB is also set.
$wgSharedTables[] = "actor";

## Shared memory settings
$wgMainCacheType = CACHE_MEMCACHED;
$wgMemCachedServers = [ '127.0.0.1:11211' ];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = true;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale. This should ideally be set to an English
## language locale so that the behaviour of C library functions will
## be consistent with typical installations. Use $wgLanguageCode to
## localise the wiki.
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "zh-cn";

$wgSecretKey = "1ac580a91a5315d1e9a5e7f30411b8bad200c8962017fbc4f109b2971bbdf15f";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

# Site upgrade key. Must be set to a string (default provided) to turn on the
# web installer while LocalSettings.php is in place
$wgUpgradeKey = "148d08610b3f2f8c";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "https://creativecommons.org/licenses/by-sa/4.0/";
$wgRightsText = "知识共享署名-相同方式共享";
$wgRightsIcon = "$wgResourceBasePath/resources/assets/licenses/cc-by-sa.png";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = 'Timeless';
$wgMFDefaultSkinClass = 'SkinMinerva';

# Enabled skins.
# The following skins were automatically enabled:
wfLoadSkin( 'Timeless' );
wfLoadSkin( 'Vector' );
wfLoadSkin( 'MinervaNeue' );

# Enabled extensions. Most of the extensions are enabled by adding
# wfLoadExtension( 'ExtensionName' );
# to LocalSettings.php. Check specific extension documentation for more details.
# The following extensions were automatically enabled:
wfLoadExtension( 'CategoryTree' );
wfLoadExtension( 'Cite' );
wfLoadExtension( 'CiteThisPage' );
wfLoadExtension( 'CodeEditor' );
wfLoadExtension( 'ConfirmEdit' );
wfLoadExtension( 'Gadgets' );
wfLoadExtension( 'ImageMap' );
wfLoadExtension( 'InputBox' );
wfLoadExtension( 'Interwiki' );
wfLoadExtension( 'LocalisationUpdate' );
wfLoadExtension( 'MultimediaViewer' );
wfLoadExtension( 'Nuke' );
wfLoadExtension( 'OATHAuth' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'ParserFunctions' );
wfLoadExtension( 'PdfHandler' );
wfLoadExtension( 'Poem' );
wfLoadExtension( 'Renameuser' );
wfLoadExtension( 'ReplaceText' );
wfLoadExtension( 'Scribunto' );
wfLoadExtension( 'SecureLinkFixer' );
wfLoadExtension( 'SpamBlacklist' );
wfLoadExtension( 'TemplateData' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'TitleBlacklist' );
wfLoadExtension( 'WikiEditor' );
wfLoadExtension( 'MobileFrontend' );
wfLoadExtension( 'ArticleCreationWorkflow' );
wfLoadExtension( 'RelatedArticles' );
wfLoadExtension( 'Echo' );
wfLoadExtension( 'Thanks' );
wfLoadExtension( 'TextExtracts' );
wfLoadExtension( 'PageImages' );
wfLoadExtension( 'Popups' );
wfLoadExtension( 'RevisionSlider' );
wfLoadExtension( 'TemplateWizard' );
wfLoadExtension( 'TabberNeue' );
wfLoadExtension( 'WikiSEO' );
wfLoadExtension( 'JsonConfig' );
wfLoadExtension( 'Graph' );
wfLoadExtension( 'TemplateStyles' );
wfLoadExtension( 'NativeSvgHandler' );

# End of automatically generated settings.
# Add more configuration options below.

## 网站图标
$wgFavicon = "$wgResourceBasePath/resources/assets/favicon.ico";

## Apple电子设备图标
$wgAppleTouchIcon = "$wgResourceBasePath/resources/assets/apple-touch-icon.png";

$wgMFAutodetectMobileView = true;

$wgExternalLinkTarget = '_blank';

$wgFileExtensions = array("png", "gif", "jpg", "jpeg", "svg");

#页脚图片
$wgFooterIcons['THMwiki']['myicon'] = [
	"src" => "https://wiki.thfmu.com/images/4/43/THMwiki_132x47.png",
    // you may also use a direct path to the source, e.g. "http://example.com/my/custom/path/to/MyCustomLogo.png"
	"url" => "https://wiki.thfmu.com/",
	"alt" => "THMwiki",
	// For HiDPI support, you can specify paths to larger versions of the icon.
	"srcset" =>
		"https://wiki.thfmu.com/images/4/43/THMwiki_132x47.png 1.5x, " .
		"https://wiki.thfmu.com/images/4/43/THMwiki_132x47.png 2x",
	// If you have a non-default sized icon you can specify the size yourself.
	"height" => "31",
	"width" => "88",
];

$wgHooks['SkinAddFooterLinks'][] = function ( Skin $skin, string $key, array &$footerlinks ) {
    if ( $key === 'places' ) {
        $footerlinks['test'] = Html::element( 'a',
            [
                'href' => 'https://beian.miit.gov.cn/',
                'rel' => '苏ICP备2022030207号-1'
            ],
        $skin->msg( '苏ICP备2022030207号-1' )->text()
        );
    };
};

$wgFileExtensions[] = 'svg';
$wgAllowTitlesInSVG = true;

## MOBILE MENU MinervaNeue
// adds upload menu item with upload icon to discovery menu.
// adds upload menu item with upload icon to discovery menu.


define("PROJECT", 3000); 
define("PROJECT_TALK", 3001); 

$wgExtraNamespaces[PROJECT] = "专题";
$wgExtraNamespaces[PROJECT_TALK] = "专题讨论"; 

define("PORTAL", 3002); 
define("PORTAL_TALK", 3003); 

$wgExtraNamespaces[PORTAL] = "门户";
$wgExtraNamespaces[PORTAL_TALK] = "门户讨论"; 

define("PROJECT_MOBILE", 3004); 
define("PROJECT_TALK_MOBILE", 3005); 

$wgExtraNamespaces[PROJECT_MOBILE] = "Pr";//专题3000的移动版本
$wgExtraNamespaces[PROJECT_TALK_MOBILE] = "PrTalk"; //专题讨论3001的移动版本